### ISSUE TITLE
Редактор мнемосхем

### ISSUE THREAD

**Issue by goodspeed1986** [intrahouseio/Doc#17]
- Возможность перевернуть текст на 90 градусов
- Изменение цвета stroke (линий) изображения svg.
- Выравнивание элементов по нижнему краю относительно друг друга

**Comment by fast0490f** [comment]
Привет @goodspeed1986,
Мы рады, что вы хотите внести вклад в наш проект. :tada: 
Для простоты отслеживания вопросы были разбиты на отдельные дискуссии. 
Также можно ознакомиться с ходом выполнения по [milestones](https://github.com/intrahouseio/Doc/milestones).
