### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by goodspeed1986** [intrahouseio/Doc#18]
- При увеличении мнемосхемы, нет возможности передвинутся из центра изображения
- Размер текста в квадратной рамке не по центру
- На мобильных устройствах на мнемосхеме текст (цифры в рамке) не масштабируются вместе с рамкой, остаются огромные
- Затемнить область интерфейса при потери связи браузера с сервером, так как не понятно есть ли связь с сервером
- В браузере Mozilla не работает кнопка Во Весь Экран

**Comment by fast0490f** [comment]
#3

**Comment by fast0490f** [comment]
#3

**Comment by fast0490f** [comment]
Привет @goodspeed1986,
Мы рады, что вы хотите внести вклад в наш проект. :tada: 
Для просты отслеживания вопросы были разбиты на отдельные дискуссии. 
Также можно ознакомиться с ходом выполнения дискусий по [milestones](https://github.com/intrahouseio/Doc/milestones).
