### ISSUE TITLE
Значение устройства в текстовом виде  расположено не по центру

### ISSUE THREAD

**Issue by nimargolis** [intrahouseio/Doc#2]
Сдвиг к нижнему краю

**Comment by fast0490f** [comment]
Привет @goodspeed1986,
Мы рады сообщить, что работа по данной задаче завершена. :rocket:
В скором времени мы выпустим новую версию, где можно будет проверить функционал.
Отследить новые версии и список изменений можно по [releases](https://github.com/intrahouseio/Doc/releases) или [milestones](https://github.com/intrahouseio/Doc/milestones). Не стесняйтесь возобновить задачу если у вас появятся вопросы.
