### ISSUE TITLE
Изменение цвета stroke (линий) изображения svg.

### ISSUE THREAD

**Issue by goodspeed1986** [intrahouseio/Doc#24]
Добавить возможность изменять цвет не только свойства fill, но и свойства stroke.

**Comment by fast0490f** [comment]
Привет @goodspeed1986,
Мы рады, что вы хотите внести вклад в наш проект. :tada: 
Я думаю, что это хорошая идея, и для эксперимента стоит попробовать реализовать данный функционал. В скором времени мы добавим эту задачу в наш план, где можно ознакомиться с ходом выполнения по [milestones](https://github.com/intrahouseio/Doc/milestones).

**Comment by fast0490f** [comment]
Привет @goodspeed1986,
Мы рады сообщить, что работа по данной задаче завершена. :rocket:
В скором времени мы выпустим новую версию, где можно будет проверить функционал.
Отследить новые версии и список изменений можно по [releases](https://github.com/intrahouseio/Doc/releases) или [milestones](https://github.com/intrahouseio/Doc/milestones). Не стесняйтесь возобновить задачу если у вас появятся вопросы.
