### ISSUE TITLE
Затемнить экран при потере связи с сервером

### ISSUE THREAD

**Issue by nimargolis** [intrahouseio/Doc#3]
Максим Вершинин: не понятно, есть ли связь с сервером

**Comment by fast0490f** [comment]
Связанная дискуссия #18

**Comment by fast0490f** [comment]
Привет @goodspeed1986,
Мы рады сообщить, что по данной дискуссии были завершены работы. :rocket:
В скором времени мы выпустим новую версию, где можно будет проверить функционал.
Отследить новые версии и список изменений можно по [releases](https://github.com/intrahouseio/Doc/releases) или [milestones](https://github.com/intrahouseio/Doc/milestones). Не стесняйтесь возобновить дискуссию если у вас появятся вопросы.
